# Generated by Django 5.2.1 on 2025-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='accesorio',
            field=models.CharField(default='Sin accesorio', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='fechaDeDevolucion',
            field=models.DateField(default='2025-06-17'),
        ),
        migrations.AddField(
            model_name='product',
            name='fechaDeEvento',
            field=models.DateField(default='2025-06-17'),
        ),
        migrations.AddField(
            model_name='product',
            name='fechaDeRegistro',
            field=models.DateField(default='2025-06-17'),
        ),
        migrations.AddField(
            model_name='product',
            name='largoDeManga',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='largoDePantalon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='nombre',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='tallaDePantalon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tallaDeSaco',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
